all: icpc
icpc:
	icpc -std=c++17 -Wall -Wextra -axIVYBRIDGE,HASWELL,BROADWELL,SKYLAKE,SKYLAKE-AVX512 -O3 -fp-model strict  main_tp0_all.cpp  -o a
g++:
	g++ -std=c++17 -Wall -Wextra -O3 -march=native  main_tp0_all.cpp  -o a
